# Generated by Django 4.1.1 on 2023-03-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSchvalovatele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, unique=True, verbose_name='název')),
                ('popis', models.CharField(blank=True, max_length=300, null=True, verbose_name='popis')),
                ('poradi', models.PositiveSmallIntegerField(default=1, verbose_name='pořadí v menu')),
                ('kde_zadat', models.CharField(choices=[('i10', 'i10 - Produkty'), ('i20', 'i20 - Schvalovatelé'), ('i30', 'i30 - Analýza'), ('i40', 'i40 - Rozhodnutí'), ('i50', 'i50 - Realizace'), ('i80', 'i80 - Uvolnění'), ('i90', 'i90 - Uzavření')], help_text='v jakém milniku zadán', max_length=50, verbose_name='kde zadat člena')),
                ('aktivni', models.BooleanField(default=True, help_text='bude role přímo v milníku vytvořena? pokud ne, pak ji lze zvolit v dodatečných rolích', verbose_name='aktivní')),
                ('povinna', models.BooleanField(default=False, help_text='bude přiřazení zaměstnance k roli (pokud bude přidána do milníku) vyžadováno ke schválení milníku?', verbose_name='povinná')),
            ],
            options={
                'verbose_name': 'role schvalovatele',
                'verbose_name_plural': 'role schvalovatelů',
                'ordering': ('kde_zadat', '-aktivni', 'poradi', 'nazev'),
            },
        ),
        migrations.CreateModel(
            name='Stredisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='název')),
                ('poradi', models.PositiveSmallIntegerField(default=1, verbose_name='pořadí v menu')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivni')),
            ],
            options={
                'verbose_name': 'středisko',
                'verbose_name_plural': 'střediska',
                'ordering': ('-aktivni', 'poradi', 'nazev'),
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='název')),
            ],
            options={
                'verbose_name': 'zákazník',
                'verbose_name_plural': 'zákazníci',
                'ordering': ('nazev',),
            },
        ),
        migrations.CreateModel(
            name='RoleSchvalovateleProduktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='název role')),
                ('poradi', models.PositiveSmallIntegerField(default=1, verbose_name='pořadí v menu')),
                ('popis', models.CharField(blank=True, max_length=300, null=True, verbose_name='popis')),
                ('aktivni', models.BooleanField(default=True, help_text='bude přímo nabízeo v i20?', verbose_name='aktivni')),
                ('stredisko', models.ForeignKey(blank=True, help_text='omezuje vyber nabizenych zamestanancu do role', null=True, on_delete=django.db.models.deletion.CASCADE, to='echm.stredisko')),
            ],
            options={
                'verbose_name': 'role schvalovatele produktu',
                'verbose_name_plural': 'role schvalovatelů produktu',
                'ordering': ('-aktivni', 'poradi', 'stredisko', 'nazev'),
                'unique_together': {('nazev', 'stredisko')},
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='název')),
                ('zakaznik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projekty', to='echm.zakaznik', verbose_name='zákazník')),
            ],
            options={
                'verbose_name': 'projekt',
                'verbose_name_plural': 'projekty',
                'ordering': ('zakaznik', 'nazev'),
                'unique_together': {('zakaznik', 'nazev')},
            },
        ),
    ]
