# Generated by Django 4.1.1 on 2023-03-27 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zmenovka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50, unique=True, verbose_name='číslo změny')),
                ('nazev', models.CharField(max_length=250, verbose_name='název změny')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='popis změny')),
                ('prinos', models.TextField(blank=True, null=True, verbose_name='přínos změny')),
                ('zadatel', models.ForeignKey(help_text='člověk, který o změnovku zažádá, ale dál ji neposouvá dále', on_delete=django.db.models.deletion.CASCADE, related_name='zadane_zmenovky', to=settings.AUTH_USER_MODEL, verbose_name='žadatel (ChR)')),
                ('zodpovedny', models.ForeignKey(help_text='člověk posunující změnovku vpřed, a mající přístup k administraci změnovky', on_delete=django.db.models.deletion.CASCADE, related_name='zodpovedne_zmenovky', to=settings.AUTH_USER_MODEL, verbose_name='zodpovědný (ChM)')),
            ],
            options={
                'verbose_name': 'Změnovka',
                'verbose_name_plural': 'Změnovky',
            },
        ),
        migrations.CreateModel(
            name='Schvalovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozhodnuti', models.CharField(blank=True, choices=[('', 'nerozhodnuto'), ('approved', 'schváleno'), ('refused', 'zamítnuto')], default='', max_length=50, null=True, verbose_name='rozhodnutí')),
                ('odpovezeno_kdy', models.DateTimeField(blank=True, help_text='kdy CCB člen odpověděl', null=True, verbose_name='odpovězeno kdy')),
                ('komentar', models.CharField(blank=True, max_length=500, null=True, verbose_name='komentář')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schvalovatele', to='echm.roleschvalovatele', verbose_name='role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schvalovatele', to=settings.AUTH_USER_MODEL, verbose_name='uživatel')),
                ('zmenovka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schvalovatele', to='i00.zmenovka')),
            ],
            options={
                'verbose_name': 'Schvalovatel',
                'verbose_name_plural': 'Schvalovatelé',
                'ordering': ('-zmenovka', 'role', 'user'),
            },
        ),
        migrations.CreateModel(
            name='PlanMilniku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('i00', 'i00 - Zadání, Milníky'), ('i10', 'i10 - Produkty'), ('i20', 'i20 - Schvalovatelé'), ('i30', 'i30 - Analýza'), ('i40', 'i40 - Rozhodnutí'), ('i50', 'i50 - Realizace'), ('i80', 'i80 - Uvolnění'), ('i90', 'i90 - Uzavření')], max_length=50, verbose_name='typ')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('planovane_datum', models.DateField(blank=True, null=True, verbose_name='plánované datum')),
                ('skutecne_datum', models.DateField(blank=True, null=True, verbose_name='skutečné datum')),
                ('zmenovka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plany_milniku', to='i00.zmenovka')),
            ],
            options={
                'verbose_name': 'Plán milníku',
                'verbose_name_plural': 'Plány milníku',
                'ordering': ('zmenovka', 'typ'),
            },
        ),
    ]
